### ISSUE TITLE
Linux支持

### ISSUE THREAD

**Issue by Amogususyy** [pa1n-dev/SMS-Bomber#1]
我试图在 Linux 上使用它，但我无法构建它，因为微软不支持 dotnet 4.8。 可以添加linux支持吗？

**Comment by Amogususyy** [comment]
我使用 mono 运行时而不是 dotnet 成功运行了发布二进制文件.
```
mono ./SMS-Bomber.exe

**Comment by pa1n-dev** [comment]
I moved the project to .net 8.0.
now you can build it for Linux
